name: "Greet User (Composite)"
description: "Greets the user by name"
inputs:
  name:
    description: 'Name of the person to greet'
    required: true
outputs:
  greeting:
    description: "The greeting message"
    value: ${{ steps.greet.outputs.greeting }}
runs:
  using: "composite"
  steps:
    - id: greet
      run: echo "greeting=Hello, ${{ inputs.name }}! 👋" >> $GITHUB_OUTPUT
      shell: bash
